### PR TITLE
chore(server): added server and database files

### PR DESCRIPTION
**Pull request by pakyardim**
- This commit adds the server and database files required for the app, as well as a sample folder structure for the server.

### CODE REVIEW

**Comment by aysuakbaba** [comment]
Well done, great commit!

**Comment by pakyardim** [comment]
**Thanks!**

**Comment by pakyardim** [comment]
> Well done, great commit!

**Thanks!**

**Comment by kaganecee** [comment]
Everyting looks good. Also, can we add root route file ( index.js ) inside folder.

**Comment by pakyardim** [comment]
> Everyting looks good. Also, can we add root route file ( index.js ) inside folder.

Will do!

**Pull request merged**
